### ISSUE TITLE
Build error in latest version 1.2.5. Version 1.1.3 works.

### ISSUE THREAD

**Issue by mithunbabu12** [misha130/ngx-drag-and-drop-lists#31] opened 2018-08-20 03:38 UTC
@misha130 - Thanks for the library.
I am getting build errors while trying to compile using the latest version of the library 1.2.5
Version 1.1.3 seems to be going through without issues.

The error is as follows. 
What version of npm will the latest versions run on?
Any ideas as to what needs to change to get it to work - 

```
> ngx-drag-and-drop-lists@1.2.5 postinstall .../jenkins/workspace/ht-question-types-left-pane-TFGXKJXDVENM5QG5I2JINYH7WFCOLVHZV2ZKTYCOJASFPEO3ZSYQ/node_modules/ngx-drag-and-drop-lists
> tsc

sh: 1: tsc: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ngx-drag-and-drop-lists@1.2.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../jenkins/.npm/_logs/2018-08-17T21_47_33_087Z-debug.log
```

Thanks

**Comment by misha130** [comment] 2018-08-20 10:58
Are you compiling the project or inside your own project?
Cause the error states you have no typescript installed

**Comment by codeunifier** [comment] 2018-09-23 17:53
Also having this issue. Going down to 1.1.3 also worked for me.

**Comment by tncho** [comment] 2018-09-27 17:53
We're also encountering this issue on our App, with versioning described below:

Angular 5.2.0
Typescript 2.6.2
RxJS 5.5.6

Do you happen to have any fix for this? As we'd like to keep our libraries updated. Thanks!

**Comment by misha130** [comment] 2018-09-27 18:38
I went on and installed your versions on the demo project and could not reproduce the issue.
It may be related to the fact that my angular CLI is 6.0.0+.
I know its bad advice but maybe try upgrading to Angular 6

**Comment by tncho** [comment] 2018-09-27 21:40
I'll give it a shot and get back to you on that one, thanks again :)

**Comment by tncho** [comment] 2018-10-02 23:42
Hey there, @misha130 ! Sadly upgrading Angular with those versions didn't work either. Do you happen to know if I can provide any other input that might be helpful?
Dropping back to previous version in the meantime. Thanks anyway! 🛠

**Comment by chrishawn** [comment] 2018-10-17 16:05
a few spots hang it up in  ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc` step all in dasherize

```
../../angular_material_schematics-V28dYW/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts:1:174 - error TS1005: ';' expected.

1 import { Component, OnInit, ViewChild<% if(!!viewEncapsulation) { %>, ViewEncapsulation<% }%><% if(changeDetection !== 'Default') { %>, ChangeDetectionStrategy<% }%> } from '@angular/core';
```

also similar errors on lines 1, 3, 6, 7, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 50

```
../../angular_material_schematics-V28dYW/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts:50:47 - error TS1109: Expression expected.

50:     this.dataSource = new <%= classify(name) %>DataSource(this.paginator, this.sort);
```

guessing it's related to the <% %>

**Comment by balajiks** [comment] 2020-02-05 05:17
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ngx-drag-and-drop-lists@1.2.5 postinstall script.

**Comment by cannontechnology** [comment] 2021-10-04 13:47
postinstall: `tsc` removed in v1.3.3

**Closed as completed by cannontechnology** 2021-10-04 13:47 UTC
